import { TithiEntry } from './schema'

/**
 * The tithi lexicon (Phase 1 Wave B). Keyed by the engine's stable tithi index
 * 0..29, mirroring name/paksha/category exactly from TITHI_DOMAIN in ./domains.
 *
 * A tithi is one lunar day — the span across which the Moon gains (shukla) or
 * loses (krishna) twelve degrees of separation from the Sun. Each carries a
 * traditional presiding deity (adhidevata, tied to the tithi number and so
 * shared across both pakshas), and belongs to one of five categories that cycle
 * Nanda (delight) → Bhadra (wholesome) → Jaya (momentum) → Rikta (emptying) →
 * Purna (fullness). Index 14 is Purnima (the full moon); index 29 is Amavasya
 * (the new moon), whose complete dark the domain marks as Purna.
 *
 * The `invitation` is always an observation, never an instruction — witnessing,
 * not counsel.
 */
export const TITHI_LEXICON: Record<number, TithiEntry> = {
  0: {
    name: 'Pratipada (Shukla)',
    paksha: 'shukla',
    category: 'Nanda',
    deity: 'Agni',
    motion: 'the first thin thread of waxing light',
    keynote: 'A first spark catches, bright with the gladness of beginning again.',
    invitation: 'You might notice a small readiness stirring, as if something in you wants to begin.',
  },
  1: {
    name: 'Dwitiya (Shukla)',
    paksha: 'shukla',
    category: 'Bhadra',
    deity: 'Brahma',
    motion: 'the waxing crescent broadening',
    keynote: 'Foundations settle into place, wholesome and quietly creative.',
    invitation: 'There may be a quiet wish to build on what was started, steady and unforced.',
  },
  2: {
    name: 'Tritiya (Shukla)',
    paksha: 'shukla',
    category: 'Jaya',
    deity: 'Gauri',
    motion: 'waxing light steadily gathering',
    keynote: 'Grace gathers momentum, tender strength moving toward what it loves.',
    invitation: 'Something in you may lean, gently, toward what it holds dear.',
  },
  3: {
    name: 'Chaturthi (Shukla)',
    paksha: 'shukla',
    category: 'Rikta',
    deity: 'Ganesha',
    motion: 'the crescent thickening toward the half',
    keynote: 'An obstacle loosens and falls away, clearing the path ahead.',
    invitation: 'You might notice a weight easing, a little more room where an obstacle had been.',
  },
  4: {
    name: 'Panchami (Shukla)',
    paksha: 'shukla',
    category: 'Purna',
    deity: 'Nagas (serpent powers)',
    motion: 'waxing light approaching the quarter',
    keynote: 'A coiled, watchful fullness rises, wise and unhurried.',
    invitation: 'There may be a watchful, coiled patience in you, waiting without hurry.',
  },
  5: {
    name: 'Shashthi (Shukla)',
    paksha: 'shukla',
    category: 'Nanda',
    deity: 'Kartikeya (Skanda)',
    motion: 'the bright crescent nearly half-filled',
    keynote: 'A bright valor delights in itself, keen and full of play.',
    invitation: 'You might notice a bright, playful energy that enjoys its own keenness.',
  },
  6: {
    name: 'Saptami (Shukla)',
    paksha: 'shukla',
    category: 'Bhadra',
    deity: 'Surya',
    motion: 'waxing light at the brink of the half',
    keynote: 'Steady warmth nourishes, luminous and wholesome.',
    invitation: 'There may be a warmth in you that feels nourished simply by the light.',
  },
  7: {
    name: 'Ashtami (Shukla)',
    paksha: 'shukla',
    category: 'Jaya',
    deity: 'Rudra',
    motion: 'the first-quarter half, exactly half-lit and climbing',
    keynote: 'Balanced at the half, a fierce clarity claims its ground.',
    invitation: 'Something in you may feel poised at a threshold, clear and evenly balanced.',
  },
  8: {
    name: 'Navami (Shukla)',
    paksha: 'shukla',
    category: 'Rikta',
    deity: 'Durga',
    motion: 'the waxing gibbous swelling past half',
    keynote: 'A cleansing fire burns away what no longer serves.',
    invitation: 'You might notice an urge to let something burn away, and a lightness where it clears.',
  },
  9: {
    name: 'Dashami (Shukla)',
    paksha: 'shukla',
    category: 'Purna',
    deity: 'Yama (Dharmaraja)',
    motion: 'waxing light broadening toward fullness',
    keynote: 'An upright fullness holds, weighted with quiet order.',
    invitation: 'There may be a sense of uprightness in you, quietly holding its own order.',
  },
  10: {
    name: 'Ekadashi (Shukla)',
    paksha: 'shukla',
    category: 'Nanda',
    deity: 'Vishvedevas',
    motion: 'the gibbous arc filling steadily',
    keynote: 'A subtle gladness turns inward, light and devotional.',
    invitation: 'Something in you may turn inward, gladdened by what is subtle rather than loud.',
  },
  11: {
    name: 'Dwadashi (Shukla)',
    paksha: 'shukla',
    category: 'Bhadra',
    deity: 'Vishnu (Hari)',
    motion: 'waxing light nearing its brim',
    keynote: 'A sustaining calm preserves, wholesome and abiding.',
    invitation: 'There may be a sustaining calm in you that asks for nothing more.',
  },
  12: {
    name: 'Trayodashi (Shukla)',
    paksha: 'shukla',
    category: 'Jaya',
    deity: 'Kamadeva',
    motion: 'the bright disc almost whole',
    keynote: 'Desire quickens toward its beauty, ardent and near-complete.',
    invitation: 'You might notice desire quickening, drawn toward a beauty almost within reach.',
  },
  13: {
    name: 'Chaturdashi (Shukla)',
    paksha: 'shukla',
    category: 'Rikta',
    deity: 'Kali',
    motion: 'waxing light on the cusp of full',
    keynote: 'On the brink of fullness, a fierce edge dissolves the last resistance.',
    invitation: 'There may be a fierce edge in you, ready to loosen the last of what clings.',
  },
  14: {
    name: 'Purnima',
    paksha: 'shukla',
    category: 'Purna',
    deity: 'Chandra (Soma)',
    motion: 'the disc entire, brimming at its fullest',
    keynote: 'Everything brims at once, radiant and wholly present.',
    invitation: 'You might notice a fullness in you, everything present and brimming at once.',
  },
  15: {
    name: 'Pratipada (Krishna)',
    paksha: 'krishna',
    category: 'Nanda',
    deity: 'Agni',
    motion: 'the first ebb from fullness',
    keynote: 'The first ebb carries an easy gladness, releasing what was full.',
    invitation: 'There may be an easy release in you, gladly letting go of what had filled up.',
  },
  16: {
    name: 'Dwitiya (Krishna)',
    paksha: 'krishna',
    category: 'Bhadra',
    deity: 'Brahma',
    motion: 'the waning gibbous beginning to thin',
    keynote: 'A gentle unmaking settles, wholesome in its letting-go.',
    invitation: 'Something in you may soften into letting-go, wholesome and unhurried.',
  },
  17: {
    name: 'Tritiya (Krishna)',
    paksha: 'krishna',
    category: 'Jaya',
    deity: 'Gauri',
    motion: 'waning light quietly receding',
    keynote: 'Grace turns homeward, quietly triumphant in retreat.',
    invitation: 'You might notice a quiet turning-homeward, grace settling back into itself.',
  },
  18: {
    name: 'Chaturthi (Krishna)',
    paksha: 'krishna',
    category: 'Rikta',
    deity: 'Ganesha',
    motion: 'the gibbous arc narrowing',
    keynote: 'A deep clearing opens, dissolving obstacles from within.',
    invitation: 'There may be a deep inner clearing, something dissolving from within.',
  },
  19: {
    name: 'Panchami (Krishna)',
    paksha: 'krishna',
    category: 'Purna',
    deity: 'Nagas (serpent powers)',
    motion: 'waning light drawing down toward the half',
    keynote: 'A hidden fullness stirs in the dark, wise and coiled.',
    invitation: 'Something in you may stir in the dark, a hidden knowing that keeps its own counsel.',
  },
  20: {
    name: 'Shashthi (Krishna)',
    paksha: 'krishna',
    category: 'Nanda',
    deity: 'Kartikeya (Skanda)',
    motion: 'the disc thinning past gibbous',
    keynote: 'A quiet delight withdraws inward, keen even in rest.',
    invitation: 'You might notice a keen delight that has drawn inward, content in retreat.',
  },
  21: {
    name: 'Saptami (Krishna)',
    paksha: 'krishna',
    category: 'Bhadra',
    deity: 'Surya',
    motion: 'waning light nearing the half',
    keynote: 'A softening warmth nourishes as the light draws down.',
    invitation: 'There may be a softening warmth in you as the light begins to fade.',
  },
  22: {
    name: 'Ashtami (Krishna)',
    paksha: 'krishna',
    category: 'Jaya',
    deity: 'Rudra',
    motion: 'the last-quarter half, exactly half-lit and fading',
    keynote: 'Balanced again at the half, a fierce stillness holds the turn.',
    invitation: 'Something in you may feel poised at the turn, still and evenly balanced.',
  },
  23: {
    name: 'Navami (Krishna)',
    paksha: 'krishna',
    category: 'Rikta',
    deity: 'Durga',
    motion: 'the waning crescent slipping past half',
    keynote: 'A fierce emptying loosens the grip of what is spent.',
    invitation: 'You might notice a loosening grip, the spent and finished falling away.',
  },
  24: {
    name: 'Dashami (Krishna)',
    paksha: 'krishna',
    category: 'Purna',
    deity: 'Yama (Dharmaraja)',
    motion: 'waning light narrowing toward dark',
    keynote: 'A grave fullness descends, ordered and unhurried.',
    invitation: 'There may be a grave, settled fullness in you, descending without hurry.',
  },
  25: {
    name: 'Ekadashi (Krishna)',
    paksha: 'krishna',
    category: 'Nanda',
    deity: 'Vishvedevas',
    motion: 'the crescent thinning steadily',
    keynote: 'An inward gladness thins toward stillness, light and devotional.',
    invitation: 'Something in you may thin toward stillness, gladdened by the quiet.',
  },
  26: {
    name: 'Dwadashi (Krishna)',
    paksha: 'krishna',
    category: 'Bhadra',
    deity: 'Vishnu (Hari)',
    motion: 'waning light growing slender',
    keynote: 'A sustaining quiet abides as the arc grows slender.',
    invitation: 'There may be a sustaining quiet in you, abiding as things grow slender.',
  },
  27: {
    name: 'Trayodashi (Krishna)',
    paksha: 'krishna',
    category: 'Jaya',
    deity: 'Kamadeva',
    motion: 'the last thin arc receding',
    keynote: 'A last ardor gathers in the dusk, momentum yielding to surrender.',
    invitation: 'You might notice a last ardor gathering, momentum easing toward surrender.',
  },
  28: {
    name: 'Chaturdashi (Krishna)',
    paksha: 'krishna',
    category: 'Rikta',
    deity: 'Kali',
    motion: 'waning light nearly spent',
    keynote: 'In the deepening dark, a fierce release empties the vessel.',
    invitation: 'There may be a fierce, emptying release in you as the dark deepens.',
  },
  29: {
    name: 'Amavasya',
    paksha: 'krishna',
    category: 'Purna',
    deity: 'Pitris (the ancestors)',
    motion: 'the light fully withdrawn into dark',
    keynote: 'The dark is complete and seed-still, whole in its emptiness.',
    invitation: 'Something in you may rest in the dark, whole and seed-still, awaiting nothing.',
  },
}
