function sqlLiteral(value) {
  return `'${String(value).replaceAll("'", "''")}'`
}

function jsonLiteral(value) {
  return `${sqlLiteral(JSON.stringify(value))}::jsonb`
}

function sqlUnits(inventory) {
  return inventory.units.map((unit) => ({
    unitKey: unit.unitKey,
    unitLabel: unit.unitLabel,
    readingType: unit.readingType,
    stableReadingId: unit.stableReadingId,
    title: unit.title,
    subjects: unit.subjects,
    relationship: unit.relationship,
    source: unit.source,
    artifact: unit.artifact,
  }))
}

/**
 * Build one metadata-only, FK-ordered transaction for migration 036.
 *
 * Every ON CONFLICT path is followed by immutable-field verification. A
 * collision, deleted record, archived subject, or changed editorial state
 * aborts the transaction instead of rewriting history.
 */
export function buildArchiveUpsertSql(inventory) {
  const units = sqlUnits(inventory)
  const stats = {
    readingCount: inventory.counts.total,
    soloCount: inventory.counts.solo,
    synastryCount: inventory.counts.synastry,
    artifactCount: inventory.totals.artifacts,
    byteSize: inventory.totals.bytes,
  }

  return `-- Generated by scripts/readings/lib/archive-sql.mjs
-- Migration contract: 036_living_readings_archive
-- Metadata only: no rendered artifact bytes are stored in PostgreSQL.
BEGIN;
DO $archive_import$
DECLARE
  v_owner_id UUID;
  v_run_id UUID;
  v_source_id UUID;
  v_subject_id UUID;
  v_relationship_id UUID;
  v_reading_id UUID;
  v_artifact_id UUID;
  v_unit JSONB;
  v_subject_unit JSONB;
  v_run reading_import_runs%ROWTYPE;
  v_source reading_sources%ROWTYPE;
  v_subject_row corpus_subjects%ROWTYPE;
  v_relationship corpus_relationships%ROWTYPE;
  v_relationship_member corpus_relationship_members%ROWTYPE;
  v_reading archived_readings%ROWTYPE;
  v_reading_subject archived_reading_subjects%ROWTYPE;
  v_artifact archived_reading_artifacts%ROWTYPE;
  v_editorial archived_reading_editorial_states%ROWTYPE;
  v_editorial_count INTEGER;
BEGIN
  SELECT id INTO STRICT v_owner_id
  FROM users
  WHERE lower(email) = ${sqlLiteral(inventory.ownerEmail)};

  INSERT INTO reading_import_runs (
    owner_user_id, manifest_id, idempotency_key, manifest_schema_version,
    manifest_sha256, source_root_locator, state, stats
  ) VALUES (
    v_owner_id, ${sqlLiteral(inventory.manifestId)},
    ${sqlLiteral(inventory.idempotencyKey)}, ${sqlLiteral(inventory.schemaVersion)},
    ${sqlLiteral(inventory.manifestSha256)}, ${sqlLiteral(inventory.corpusRoot)},
    'running', ${jsonLiteral(stats)}
  )
  ON CONFLICT (owner_user_id, idempotency_key) DO NOTHING;

  SELECT * INTO STRICT v_run
  FROM reading_import_runs
  WHERE owner_user_id = v_owner_id
    AND idempotency_key = ${sqlLiteral(inventory.idempotencyKey)}
  FOR UPDATE;
  v_run_id := v_run.id;

  IF v_run.manifest_id IS DISTINCT FROM ${sqlLiteral(inventory.manifestId)}
     OR v_run.manifest_schema_version IS DISTINCT FROM ${sqlLiteral(inventory.schemaVersion)}
     OR v_run.manifest_sha256 IS DISTINCT FROM ${sqlLiteral(inventory.manifestSha256)}
     OR v_run.source_root_locator IS DISTINCT FROM ${sqlLiteral(inventory.corpusRoot)}
     OR v_run.stats IS DISTINCT FROM ${jsonLiteral(stats)}
     OR v_run.state NOT IN ('running', 'completed') THEN
    RAISE EXCEPTION 'Archive import-run collision or non-reusable state';
  END IF;

  FOR v_unit IN
    SELECT value
    FROM jsonb_array_elements(${jsonLiteral(units)})
  LOOP
    IF left(v_unit #>> '{source,locator}', length(${sqlLiteral(inventory.corpusRoot)}) + 1)
         IS DISTINCT FROM ${sqlLiteral(`${inventory.corpusRoot}/`)}
       OR left(v_unit #>> '{artifact,objectLocator}', length(${sqlLiteral(inventory.corpusRoot)}) + 1)
         IS DISTINCT FROM ${sqlLiteral(`${inventory.corpusRoot}/`)} THEN
      RAISE EXCEPTION 'Archive locator escapes the canonical corpus root';
    END IF;

    INSERT INTO reading_sources (
      import_run_id, owner_user_id, stable_source_id, source_kind, locator,
      content_sha256, byte_size, media_type, metadata
    ) VALUES (
      v_run_id, v_owner_id, v_unit #>> '{source,stableSourceId}',
      v_unit #>> '{source,sourceKind}', v_unit #>> '{source,locator}',
      v_unit #>> '{source,contentSha256}',
      (v_unit #>> '{source,byteSize}')::bigint,
      v_unit #>> '{source,mediaType}',
      jsonb_build_object(
        'corpus', '723',
        'unitKey', v_unit ->> 'unitKey',
        'corpusRelativePath', v_unit #>> '{source,corpusRelativePath}',
        'consentBasis', ${sqlLiteral(inventory.consentBasis)}
      )
    )
    ON CONFLICT (import_run_id, stable_source_id) DO NOTHING;

    SELECT * INTO STRICT v_source
    FROM reading_sources
    WHERE import_run_id = v_run_id
      AND stable_source_id = v_unit #>> '{source,stableSourceId}';
    v_source_id := v_source.id;
    IF v_source.owner_user_id IS DISTINCT FROM v_owner_id
       OR v_source.source_kind IS DISTINCT FROM v_unit #>> '{source,sourceKind}'
       OR v_source.locator IS DISTINCT FROM v_unit #>> '{source,locator}'
       OR v_source.content_sha256 IS DISTINCT FROM v_unit #>> '{source,contentSha256}'
       OR v_source.byte_size IS DISTINCT FROM (v_unit #>> '{source,byteSize}')::bigint
       OR v_source.media_type IS DISTINCT FROM v_unit #>> '{source,mediaType}'
       OR v_source.metadata IS DISTINCT FROM jsonb_build_object(
         'corpus', '723',
         'unitKey', v_unit ->> 'unitKey',
         'corpusRelativePath', v_unit #>> '{source,corpusRelativePath}',
         'consentBasis', ${sqlLiteral(inventory.consentBasis)}
       ) THEN
      RAISE EXCEPTION 'Archive source collision for %', v_unit ->> 'unitKey';
    END IF;

    v_relationship_id := NULL;
    IF v_unit -> 'relationship' <> 'null'::jsonb THEN
      INSERT INTO corpus_relationships (
        owner_user_id, relationship_key, relationship_kind, label,
        reconciliation_state, metadata
      ) VALUES (
        v_owner_id, v_unit #>> '{relationship,relationshipKey}',
        v_unit #>> '{relationship,relationshipKind}',
        v_unit #>> '{relationship,relationshipLabel}',
        v_unit #>> '{relationship,reconciliationState}',
        jsonb_build_object(
          'corpus', '723',
          'unitLabel', v_unit ->> 'unitLabel',
          'identityInference', v_unit #>> '{relationship,identityInference}'
        )
      )
      ON CONFLICT (owner_user_id, relationship_key) DO NOTHING;

      SELECT * INTO STRICT v_relationship
      FROM corpus_relationships
      WHERE owner_user_id = v_owner_id
        AND relationship_key = v_unit #>> '{relationship,relationshipKey}'
      FOR UPDATE;
      v_relationship_id := v_relationship.id;
      IF v_relationship.relationship_kind IS DISTINCT FROM
           v_unit #>> '{relationship,relationshipKind}'
         OR v_relationship.label IS DISTINCT FROM
           v_unit #>> '{relationship,relationshipLabel}'
         OR v_relationship.reconciliation_state IS DISTINCT FROM
           v_unit #>> '{relationship,reconciliationState}'
         OR v_relationship.metadata IS DISTINCT FROM jsonb_build_object(
           'corpus', '723',
           'unitLabel', v_unit ->> 'unitLabel',
           'identityInference', v_unit #>> '{relationship,identityInference}'
         ) THEN
        RAISE EXCEPTION 'Archive relationship collision for %', v_unit ->> 'unitKey';
      END IF;
    END IF;

    FOR v_subject_unit IN
      SELECT value FROM jsonb_array_elements(v_unit -> 'subjects')
    LOOP
      INSERT INTO corpus_subjects (
        owner_user_id, subject_key, subject_type, canonical_name, sort_name,
        reconciliation_state, profile
      ) VALUES (
        v_owner_id, v_subject_unit ->> 'subjectKey',
        v_subject_unit ->> 'subjectType', v_subject_unit ->> 'canonicalName',
        v_subject_unit ->> 'canonicalName',
        v_subject_unit ->> 'reconciliationState',
        jsonb_build_object(
          'corpus', '723',
          'unitLabel', v_unit ->> 'unitLabel',
          'readingType', v_unit ->> 'readingType',
          'identityInference', v_subject_unit ->> 'identityInference'
        )
      )
      ON CONFLICT (owner_user_id, subject_key) DO NOTHING;

      SELECT * INTO STRICT v_subject_row
      FROM corpus_subjects
      WHERE owner_user_id = v_owner_id
        AND subject_key = v_subject_unit ->> 'subjectKey'
      FOR UPDATE;
      v_subject_id := v_subject_row.id;
      IF v_subject_row.subject_type IS DISTINCT FROM v_subject_unit ->> 'subjectType'
         OR v_subject_row.canonical_name IS DISTINCT FROM v_subject_unit ->> 'canonicalName'
         OR v_subject_row.sort_name IS DISTINCT FROM v_subject_unit ->> 'canonicalName'
         OR v_subject_row.reconciliation_state IS DISTINCT FROM
           v_subject_unit ->> 'reconciliationState'
         OR v_subject_row.profile IS DISTINCT FROM jsonb_build_object(
           'corpus', '723',
           'unitLabel', v_unit ->> 'unitLabel',
           'readingType', v_unit ->> 'readingType',
           'identityInference', v_subject_unit ->> 'identityInference'
         ) THEN
        RAISE EXCEPTION 'Archive subject collision or archived subject for %',
          v_unit ->> 'unitKey';
      END IF;

      IF v_relationship_id IS NOT NULL THEN
        INSERT INTO corpus_relationship_members (
          relationship_id, subject_id, owner_user_id, member_role, position, metadata
        ) VALUES (
          v_relationship_id, v_subject_id, v_owner_id,
          v_subject_unit ->> 'subjectRole',
          (v_subject_unit ->> 'position')::smallint,
          jsonb_build_object('corpus', '723', 'unitLabel', v_unit ->> 'unitLabel')
        )
        ON CONFLICT (relationship_id, subject_id, member_role) DO NOTHING;

        SELECT * INTO STRICT v_relationship_member
        FROM corpus_relationship_members
        WHERE relationship_id = v_relationship_id
          AND subject_id = v_subject_id
          AND member_role = v_subject_unit ->> 'subjectRole';
        IF v_relationship_member.owner_user_id IS DISTINCT FROM v_owner_id
           OR v_relationship_member.position IS DISTINCT FROM
             (v_subject_unit ->> 'position')::smallint
           OR v_relationship_member.metadata IS DISTINCT FROM
             jsonb_build_object('corpus', '723', 'unitLabel', v_unit ->> 'unitLabel') THEN
          RAISE EXCEPTION 'Archive relationship-member collision for %',
            v_unit ->> 'unitKey';
        END IF;
      END IF;
    END LOOP;

    INSERT INTO archived_readings (
      owner_user_id, import_run_id, primary_source_id, relationship_id, stable_reading_id,
      title, reading_type, language_tag, producer_kind, producer_ref,
      content_locator, content_sha256, summary, metadata
    ) VALUES (
      v_owner_id, v_run_id, v_source_id, v_relationship_id,
      v_unit ->> 'stableReadingId',
      v_unit ->> 'title', v_unit ->> 'readingType', 'en', 'imported',
      '723-completed-render',
      v_unit #>> '{artifact,objectLocator}',
      v_unit #>> '{artifact,contentSha256}',
      'Completed rendered reading imported from the protected 723 corpus.',
      jsonb_build_object(
        'corpus', '723',
        'unitKey', v_unit ->> 'unitKey',
        'unitLabel', v_unit ->> 'unitLabel',
        'consentBasis', ${sqlLiteral(inventory.consentBasis)}
      )
    )
    ON CONFLICT (owner_user_id, stable_reading_id) DO NOTHING;

    SELECT * INTO STRICT v_reading
    FROM archived_readings
    WHERE owner_user_id = v_owner_id
      AND stable_reading_id = v_unit ->> 'stableReadingId'
    FOR UPDATE;
    v_reading_id := v_reading.id;
    IF v_reading.record_state = 'deleted'
       OR v_reading.import_run_id IS DISTINCT FROM v_run_id
       OR v_reading.primary_source_id IS DISTINCT FROM v_source_id
       OR v_reading.relationship_id IS DISTINCT FROM v_relationship_id
       OR v_reading.title IS DISTINCT FROM v_unit ->> 'title'
       OR v_reading.reading_type IS DISTINCT FROM v_unit ->> 'readingType'
       OR v_reading.language_tag IS DISTINCT FROM 'en'
       OR v_reading.producer_kind IS DISTINCT FROM 'imported'
       OR v_reading.producer_ref IS DISTINCT FROM '723-completed-render'
       OR v_reading.content_locator IS DISTINCT FROM v_unit #>> '{artifact,objectLocator}'
       OR v_reading.content_sha256 IS DISTINCT FROM v_unit #>> '{artifact,contentSha256}'
       OR v_reading.summary IS DISTINCT FROM
         'Completed rendered reading imported from the protected 723 corpus.'
       OR v_reading.metadata IS DISTINCT FROM jsonb_build_object(
         'corpus', '723',
         'unitKey', v_unit ->> 'unitKey',
         'unitLabel', v_unit ->> 'unitLabel',
         'consentBasis', ${sqlLiteral(inventory.consentBasis)}
       ) THEN
      RAISE EXCEPTION 'Archive reading collision or deleted record for %', v_unit ->> 'unitKey';
    END IF;

    FOR v_subject_unit IN
      SELECT value FROM jsonb_array_elements(v_unit -> 'subjects')
    LOOP
      SELECT * INTO STRICT v_subject_row
      FROM corpus_subjects
      WHERE owner_user_id = v_owner_id
        AND subject_key = v_subject_unit ->> 'subjectKey';
      v_subject_id := v_subject_row.id;

      INSERT INTO archived_reading_subjects (
        reading_id, subject_id, owner_user_id, subject_role, confidence, note
      ) VALUES (
        v_reading_id, v_subject_id, v_owner_id,
        v_subject_unit ->> 'subjectRole', 1.0,
        CASE
          WHEN v_unit ->> 'readingType' = 'synastry'
            THEN 'Candidate participant preserved from the canonical completed reading'
          ELSE 'Canonical Solo unit label'
        END
      )
      ON CONFLICT (reading_id, subject_id, subject_role) DO NOTHING;
      SELECT * INTO STRICT v_reading_subject
      FROM archived_reading_subjects
      WHERE reading_id = v_reading_id
        AND subject_id = v_subject_id
        AND subject_role = v_subject_unit ->> 'subjectRole';
      IF v_reading_subject.owner_user_id IS DISTINCT FROM v_owner_id
         OR v_reading_subject.confidence IS DISTINCT FROM 1.0
         OR v_reading_subject.note IS DISTINCT FROM (CASE
           WHEN v_unit ->> 'readingType' = 'synastry'
             THEN 'Candidate participant preserved from the canonical completed reading'
           ELSE 'Canonical Solo unit label'
         END) THEN
        RAISE EXCEPTION 'Archive subject-link collision for %', v_unit ->> 'unitKey';
      END IF;
    END LOOP;

    INSERT INTO archived_reading_artifacts (
      reading_id, owner_user_id, artifact_key, artifact_role, storage_provider,
      object_locator, content_sha256, byte_size, media_type,
      availability_state, metadata
    ) VALUES (
      v_reading_id, v_owner_id, v_unit #>> '{artifact,artifactKey}',
      v_unit #>> '{artifact,artifactRole}', 'filesystem',
      v_unit #>> '{artifact,objectLocator}',
      v_unit #>> '{artifact,contentSha256}',
      (v_unit #>> '{artifact,byteSize}')::bigint,
      v_unit #>> '{artifact,mediaType}', 'available',
      jsonb_build_object(
        'corpus', '723',
        'unitKey', v_unit ->> 'unitKey',
        'selection', v_unit #>> '{artifact,selection}',
        'corpusRelativePath', v_unit #>> '{source,corpusRelativePath}'
      )
    )
    ON CONFLICT (reading_id, artifact_key) DO NOTHING;

    SELECT * INTO STRICT v_artifact
    FROM archived_reading_artifacts
    WHERE reading_id = v_reading_id
      AND artifact_key = v_unit #>> '{artifact,artifactKey}'
    FOR UPDATE;
    v_artifact_id := v_artifact.id;
    IF v_artifact.availability_state = 'deleted'
       OR v_artifact.owner_user_id IS DISTINCT FROM v_owner_id
       OR v_artifact.artifact_role IS DISTINCT FROM v_unit #>> '{artifact,artifactRole}'
       OR v_artifact.storage_provider IS DISTINCT FROM 'filesystem'
       OR v_artifact.object_locator IS DISTINCT FROM v_unit #>> '{artifact,objectLocator}'
       OR v_artifact.content_sha256 IS DISTINCT FROM v_unit #>> '{artifact,contentSha256}'
       OR v_artifact.byte_size IS DISTINCT FROM (v_unit #>> '{artifact,byteSize}')::bigint
       OR v_artifact.media_type IS DISTINCT FROM v_unit #>> '{artifact,mediaType}'
       OR v_artifact.availability_state IS DISTINCT FROM 'available'
       OR v_artifact.metadata IS DISTINCT FROM jsonb_build_object(
         'corpus', '723',
         'unitKey', v_unit ->> 'unitKey',
         'selection', v_unit #>> '{artifact,selection}',
         'corpusRelativePath', v_unit #>> '{source,corpusRelativePath}'
       ) THEN
      RAISE EXCEPTION 'Archive artifact collision or deleted record for %', v_unit ->> 'unitKey';
    END IF;

    SELECT count(*) INTO v_editorial_count
    FROM archived_reading_editorial_states
    WHERE reading_id = v_reading_id;
    SELECT * INTO v_editorial
    FROM archived_reading_editorial_states
    WHERE reading_id = v_reading_id AND is_current;

    IF NOT FOUND THEN
      IF v_editorial_count <> 0 THEN
        RAISE EXCEPTION 'Archive editorial history has no current state for %', v_unit ->> 'unitKey';
      END IF;
      INSERT INTO archived_reading_editorial_states (
        reading_id, owner_user_id, state, visibility, changed_by_user_id,
        change_role, revision, is_current, rationale
      ) VALUES (
        v_reading_id, v_owner_id, 'approved', 'owner_only', v_owner_id,
        'importer', 1, true,
        'Owner-confirmed completed archive import; private unless separately shared'
      );
    ELSIF v_editorial.owner_user_id IS DISTINCT FROM v_owner_id
       OR v_editorial.state IS DISTINCT FROM 'approved'
       OR v_editorial.visibility IS DISTINCT FROM 'owner_only' THEN
      RAISE EXCEPTION 'Archive editorial-state collision for %', v_unit ->> 'unitKey';
    END IF;
  END LOOP;

  UPDATE reading_import_runs
  SET state = 'completed',
      stats = ${jsonLiteral(stats)},
      finished_at = COALESCE(finished_at, NOW()),
      error_message = NULL
  WHERE id = v_run_id;
END
$archive_import$;
COMMIT;
`
}
