function sqlLiteral(value) {
  return `'${String(value).replaceAll("'", "''")}'`
}

function jsonLiteral(value) {
  return `${sqlLiteral(JSON.stringify(value))}::jsonb`
}

function artifactByRole(pilot, role) {
  const artifact = pilot.artifacts.find((candidate) => candidate.artifactRole === role)
  if (!artifact) throw new Error(`Pilot requires an ${role} artifact`)
  return artifact
}

/**
 * Produce one idempotent PostgreSQL transaction for migration 036.
 * Object bytes must already exist and have been independently checksum-verified.
 */
export function buildPilotUpsertSql(pilot, { bucket }) {
  const sourceArtifact = artifactByRole(pilot, 'source_document')
  const readingArtifact = artifactByRole(pilot, 'rendered_reading')
  const aliases = pilot.subject.aliases ?? []
  const artifactStatements = pilot.artifacts
    .map(
      (artifact) => `
    INSERT INTO archived_reading_artifacts (
      reading_id, owner_user_id, artifact_key, artifact_role, storage_provider,
      object_locator, content_sha256, byte_size, media_type, availability_state, metadata
    ) VALUES (
      v_reading_id, v_owner_id, ${sqlLiteral(artifact.artifactKey)},
      ${sqlLiteral(artifact.artifactRole)}, 'r2',
      ${sqlLiteral(`r2://${bucket}/${artifact.objectKey}`)},
      ${sqlLiteral(artifact.sha256)}, ${artifact.bytes.length},
      ${sqlLiteral(artifact.mediaType)}, 'available',
      ${jsonLiteral({ corpusRelativePath: artifact.relativePath, pilotId: pilot.pilotId })}
    )
    ON CONFLICT (reading_id, artifact_key) DO UPDATE SET
      object_locator = EXCLUDED.object_locator,
      content_sha256 = EXCLUDED.content_sha256,
      byte_size = EXCLUDED.byte_size,
      media_type = EXCLUDED.media_type,
      metadata = EXCLUDED.metadata,
      updated_at = NOW();`,
    )
    .join('\n')
  const aliasStatements = aliases
    .map(
      (alias) => `
    INSERT INTO corpus_subject_aliases (
      subject_id, source_id, owner_user_id, alias, normalized_alias, alias_kind, review_state
    ) VALUES (
      v_subject_id, v_source_id, v_owner_id, ${sqlLiteral(alias)},
      ${sqlLiteral(alias.normalize('NFC').toLocaleLowerCase('en-US'))},
      'identifier', 'verified'
    )
    ON CONFLICT (subject_id, normalized_alias) DO NOTHING;`,
    )
    .join('\n')

  return `-- Generated by scripts/readings/lib/pilot-sql.mjs
-- Pilot: ${pilot.pilotId}
-- This transaction stores metadata only. Artifact bytes must already exist.
BEGIN;
DO $pilot$
DECLARE
  v_owner_id UUID;
  v_run_id UUID;
  v_source_id UUID;
  v_subject_id UUID;
  v_reading_id UUID;
  v_record_state VARCHAR(16);
BEGIN
  SELECT id INTO STRICT v_owner_id
  FROM users
  WHERE lower(email) = ${sqlLiteral(pilot.ownerEmail)};

  INSERT INTO reading_import_runs (
    owner_user_id, manifest_id, idempotency_key, manifest_schema_version,
    manifest_sha256, source_root_locator, state, stats
  ) VALUES (
    v_owner_id, ${sqlLiteral(pilot.manifestId)}, ${sqlLiteral(pilot.idempotencyKey)},
    ${sqlLiteral(String(pilot.schemaVersion))}, ${sqlLiteral(pilot.manifestSha256)},
    ${sqlLiteral(`corpus://723/${pilot.corpusRelativeRoot}`)}, 'running',
    ${jsonLiteral({ pilotId: pilot.pilotId, artifactCount: pilot.artifacts.length })}
  )
  ON CONFLICT (owner_user_id, idempotency_key) DO UPDATE SET updated_at = NOW()
  RETURNING id INTO v_run_id;

  INSERT INTO reading_sources (
    import_run_id, owner_user_id, stable_source_id, source_kind, locator,
    content_sha256, byte_size, media_type, observed_at, metadata
  ) VALUES (
    v_run_id, v_owner_id, ${sqlLiteral(`pilot-source:${sourceArtifact.artifactKey}`)},
    'manifest', ${sqlLiteral(`corpus://723/${pilot.corpusRelativeRoot}/${sourceArtifact.relativePath}`)},
    ${sqlLiteral(sourceArtifact.sha256)}, ${sourceArtifact.bytes.length},
    ${sqlLiteral(sourceArtifact.mediaType)}, ${sqlLiteral(pilot.reading.capturedAt)}::timestamptz,
    ${jsonLiteral({ pilotId: pilot.pilotId, consent: pilot.consent })}
  )
  ON CONFLICT (import_run_id, stable_source_id) DO UPDATE SET
    locator = EXCLUDED.locator,
    content_sha256 = EXCLUDED.content_sha256,
    byte_size = EXCLUDED.byte_size,
    media_type = EXCLUDED.media_type,
    metadata = EXCLUDED.metadata
  RETURNING id INTO v_source_id;

  INSERT INTO corpus_subjects (
    owner_user_id, subject_key, canonical_name, sort_name,
    reconciliation_state, profile
  ) VALUES (
    v_owner_id, ${sqlLiteral(pilot.subject.subjectKey)},
    ${sqlLiteral(pilot.subject.canonicalName)}, ${sqlLiteral(pilot.subject.canonicalName)},
    'verified', ${jsonLiteral({ consent: pilot.consent })}
  )
  ON CONFLICT (owner_user_id, subject_key) DO UPDATE SET
    canonical_name = EXCLUDED.canonical_name,
    sort_name = EXCLUDED.sort_name,
    reconciliation_state = 'verified',
    profile = EXCLUDED.profile
  RETURNING id INTO v_subject_id;
${aliasStatements}

  SELECT id, record_state INTO v_reading_id, v_record_state
  FROM archived_readings
  WHERE owner_user_id = v_owner_id
    AND stable_reading_id = ${sqlLiteral(pilot.reading.stableReadingId)};

  IF v_reading_id IS NULL THEN
    INSERT INTO archived_readings (
      owner_user_id, import_run_id, primary_source_id, stable_reading_id,
      title, reading_type, language_tag, producer_kind, producer_ref,
      content_locator, content_sha256, summary, metadata, captured_at
    ) VALUES (
      v_owner_id, v_run_id, v_source_id, ${sqlLiteral(pilot.reading.stableReadingId)},
      ${sqlLiteral(pilot.reading.title)}, ${sqlLiteral(pilot.reading.readingType)},
      ${sqlLiteral(pilot.reading.languageTag)}, ${sqlLiteral(pilot.reading.producerKind)},
      ${sqlLiteral(pilot.reading.producerRef)},
      ${sqlLiteral(`r2://${bucket}/${readingArtifact.objectKey}`)},
      ${sqlLiteral(readingArtifact.sha256)}, ${sqlLiteral(pilot.reading.summary)},
      ${jsonLiteral({ pilotId: pilot.pilotId, consent: pilot.consent })},
      ${sqlLiteral(pilot.reading.capturedAt)}::timestamptz
    )
    RETURNING id INTO v_reading_id;
  ELSIF v_record_state = 'deleted' THEN
    RAISE EXCEPTION 'Pilot reading was deleted; explicit restore is required';
  ELSE
    UPDATE archived_readings SET
      import_run_id = v_run_id,
      primary_source_id = v_source_id,
      title = ${sqlLiteral(pilot.reading.title)},
      reading_type = ${sqlLiteral(pilot.reading.readingType)},
      content_locator = ${sqlLiteral(`r2://${bucket}/${readingArtifact.objectKey}`)},
      content_sha256 = ${sqlLiteral(readingArtifact.sha256)},
      summary = ${sqlLiteral(pilot.reading.summary)},
      metadata = ${jsonLiteral({ pilotId: pilot.pilotId, consent: pilot.consent })}
    WHERE id = v_reading_id;
  END IF;

  INSERT INTO archived_reading_subjects (
    reading_id, subject_id, owner_user_id, subject_role, confidence, note
  ) VALUES (
    v_reading_id, v_subject_id, v_owner_id, 'primary', 1.0,
    'Explicitly verified solo pilot subject'
  )
  ON CONFLICT (reading_id, subject_id, subject_role) DO NOTHING;
${artifactStatements}

  IF NOT EXISTS (
    SELECT 1 FROM archived_reading_editorial_states WHERE reading_id = v_reading_id
  ) THEN
    INSERT INTO archived_reading_editorial_states (
      reading_id, owner_user_id, state, visibility, changed_by_user_id,
      change_role, revision, is_current, rationale
    ) VALUES (
      v_reading_id, v_owner_id, ${sqlLiteral(pilot.editorial.state)},
      ${sqlLiteral(pilot.editorial.visibility)}, v_owner_id,
      'importer', 1, true, ${sqlLiteral(pilot.editorial.rationale)}
    );
  END IF;

  UPDATE reading_import_runs SET
    state = 'completed',
    stats = ${jsonLiteral({
      pilotId: pilot.pilotId,
      artifactCount: pilot.artifacts.length,
      readingCount: 1,
      subjectCount: 1,
    })},
    finished_at = COALESCE(finished_at, NOW()),
    error_message = NULL
  WHERE id = v_run_id;
END
$pilot$;
COMMIT;
`
}

export function buildPilotSoftDeleteSql(pilot) {
  return `-- Soft-delete pilot content while preserving import-run and source audit rows.
BEGIN;
WITH owner AS (
  SELECT id FROM users WHERE lower(email) = ${sqlLiteral(pilot.ownerEmail)}
), target AS (
  SELECT ar.id, ar.owner_user_id
  FROM archived_readings ar
  JOIN owner ON owner.id = ar.owner_user_id
  WHERE ar.stable_reading_id = ${sqlLiteral(pilot.reading.stableReadingId)}
)
UPDATE archived_reading_artifacts artifact
SET availability_state = 'deleted', deleted_at = NOW(), updated_at = NOW()
FROM target
WHERE artifact.reading_id = target.id
  AND artifact.owner_user_id = target.owner_user_id;

WITH owner AS (
  SELECT id FROM users WHERE lower(email) = ${sqlLiteral(pilot.ownerEmail)}
)
UPDATE archived_readings
SET record_state = 'deleted', deleted_at = NOW(), updated_at = NOW()
WHERE owner_user_id = (SELECT id FROM owner)
  AND stable_reading_id = ${sqlLiteral(pilot.reading.stableReadingId)};
COMMIT;
`
}
